function b = bar_by_group(groups, values)
%BAR_BY_GROUP Summary of this function goes here
%   Detailed explanation goes here

b = bar(values, ...
    'FaceColor', 'flat', ...
    'CData', jet(groups.m), ...
    'XData', groups.GroupCategory ...
);

end

