---
title: "Descriptive_Statistics"
author: "OMR Group 2"
date: "30-11-2020"
mainfont: Garamond
fontsize: 12pt
urlcolor: blue
output: 
  html_document:
    keep_md: yes
    latex_engine: xelatex
---

```{r load_packages}

library(ISLR)
library(dplyr)
library(tidyverse)
library(haven)
library(readxl)
library(Matrix)
library(tinytex)
library(ggplot2)
library(wesanderson)
library(png)

```

```{r setup-chunk, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      cache = TRUE)
```

Import data and check data format.
```{r 1}

data <- read.csv(unz("../data/30-11-2020.zip", "30-11-2020.csv"), header = TRUE)

Contact_matrix <- read.csv("../data/Contact_matrix.csv", header = TRUE)

class <- lapply(data,class)
```

```{r 2}
##Build contact matrix for the physical&non-physical contact of people in different age-groups in the Netherlands, taken from https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0050074

Contact_matrix <- Contact_matrix %>%
                    rename("0_4" = 1, "5_9" = 2, "10_14" = 3, "15_19" = 4, "20_24" = 5, "25_29" = 6, "30_34" = 7, "35_39" = 8, "40_44" = 9, "45_49" = 10, "50_54" = 11, "55_59" = 12, "60_64" = 13, "65_69" = 14, "70+" = 15)
```

Begin cleaning the data.
```{r 3}
#Create data frame for infection rate, hence '_i'
#Mutate 'Agegroup' to fix the formatting issue
#Mutate a further two times to plot values in order later
data_i <- data %>% 
  filter(Agegroup != "Unknown") %>%
  filter(Agegroup != "<50") %>%
  filter(Sex != "Unknown") %>%
  mutate(Agegroup=recode(Agegroup, `Oct-19` = '10-19')) %>%
  mutate(Agegroup = as.character(Agegroup)) %>%
  mutate(Agegroup = as.factor(Agegroup))

#Create data frame with infections of last 10 days
data_i10 <- data %>% 
  filter(Date_statistics == c("31/10/2020", "30/10/2020", "29/10/2020", "28/10/2020", "27/10/2020", "26/10/2020", "25/10/2020", "24/10/2020", "23/10/2020", "22/10/2020")) %>%
  filter(Agegroup != "Unknown") %>%
  filter(Agegroup != "<50") %>%
  filter(Sex != "Unknown") %>%
  mutate(Agegroup=recode(Agegroup, `Oct-19` = '10-19')) %>%
  mutate(Agegroup = as.character(Agegroup)) %>%
  mutate(Agegroup = as.factor(Agegroup))

#Create data frame for death rate, hence '_d'
data_d <- data %>%
  filter(Agegroup != "Unknown") %>%
  filter(Sex != "Unknown") %>%
  filter(!is.na(Week_of_death))
```

```{r 4}
#Plot the number of infections using 'data_i' data frame
plot_infection_agegroup <- data_i %>%
  arrange(Agegroup) %>%
  group_by(Province) %>%
  ggplot(aes(x=Province)) + 
  #guides(col=FALSE) +
  geom_bar(mapping = aes(fill = Agegroup), alpha=0.9, position = position_stack(reverse = TRUE)) + 
  scale_fill_manual(values = wes_palette("Zissou1", 10, type = "continuous")) +
  coord_flip() +
  theme_classic() +
  labs(x="Province", y="Count", 
      title="Infection rate across Age Group")
```

```{r }
#Plot the number of infections by gender
plot_infection_gender <- data_i %>%
  arrange(Sex) %>%
  group_by(Province) %>%
  ggplot(aes(x=Province)) + 
  #guides(col=FALSE) +
  geom_bar(mapping = aes(fill = Sex), alpha=0.9, position = position_stack(reverse = TRUE)) + 
  scale_fill_manual(values = wes_palette("Zissou1", 3, type = "continuous")) +
  coord_flip() +
  theme_classic() +
  labs(x="Province", y="Count", 
      title="Infection rate across Gender")
```

```{r }
#Plot the number of hospitalisations
plot_hospitalisation_agegroup <- data_i %>%
  arrange(Sex) %>%
  group_by(Agegroup) %>%
  ggplot(aes(x=Agegroup)) + 
  #guides(col=FALSE) +
  geom_bar(mapping = aes(fill = Sex), alpha=0.9, position = position_stack(reverse = TRUE)) + 
  scale_fill_manual(values = wes_palette("Zissou1", 3, type = "continuous")) +
  coord_flip() +
  theme_classic() +
  labs(x="Agegroup", y="Count", 
      title="Hospitalisation across Age Group")
```

```{r hospitalisation_age, dev = "png"}
plot_hospitalisation_agegroup
```

```{r infection_rate_age, dev = "png"}
plot_infection_agegroup
```

```{r infection_rate_gender, dev = "png"}
plot_infection_gender
```

```{r 5}
#Plot the number of deaths using the 'data_d' data frame
plot_death_agegroup <- data_d %>%
  group_by(Province) %>%
  ggplot(aes(x=Province)) + 
  #guides(col=FALSE) +
  geom_bar(mapping = aes(fill = Agegroup), alpha=0.9, position = position_stack(reverse = TRUE)) + 
  scale_fill_manual(values = wes_palette("Zissou1", 6, type = "continuous")) +
  coord_flip() +
  theme_classic() +
  labs(x="Province", y="Count", 
      title="Death rate across Age Group")
```

```{r }
#Plot the number of deaths by gender
plot_death_gender <- data_d %>%
  group_by(Province) %>%
  ggplot(aes(x=Province)) + 
  #guides(col=FALSE) +
  geom_bar(mapping = aes(fill = Sex), alpha=0.9, position = position_stack(reverse = TRUE)) + 
  scale_fill_manual(values = wes_palette("Zissou1", 3, type = "continuous")) +
  coord_flip() +
  theme_classic() +
  labs(x="Province", y="Count", 
      title="Death rate across Gender")
```

```{r death_rate, dev = "png"}
plot_death_agegroup
```

```{r death_rate_gender, dev = "png"}
plot_death_gender
```

```{r 6}
##Create matrix for proportion of infections by age group
#Extract age groups column from infections data frame
agg_i <- aggregate(data_i$Agegroup, by=list(data_i$Agegroup), FUN=length)

agg_i <- agg_i %>%
          rename("Count" = "x") %>%
          rename("Agegroup" = "Group.1") %>%
    group_by(Agegroup) %>%
    mutate(Sum = sum(agg_i$x)) %>%
    mutate(Proportion=(round(Count/Sum,4)))

#Diagonal matrix
diag_i <- Diagonal(nrow(agg_i), agg_i$Count)

#Diagonal matrix for proportion of infections
diag_i_prop <- Diagonal(nrow(agg_i), agg_i$Proportion)

##Create matrix for proportion of deaths by age group
#Extract age groups column from death rate data frame
agg_d <- aggregate(data_d$Agegroup, by=list(data_d$Agegroup), FUN=length)

agg_d <- agg_d %>%
          rename("Count" = "x") %>%
          rename("Agegroup" = "Group.1") %>%
    group_by(Agegroup) %>%
    mutate(Sum = sum(agg_d$x)) %>%
    mutate(Proportion=(round(Count/Sum,4)))

#Diagonal matrix
diag_d <- Diagonal(nrow(agg_d), agg_d$Count)

#Diagonal matrix for proportion of deaths
diag_d_prop <- Diagonal(nrow(agg_d), agg_d$Proportion)

```

```{r 7}
#Calculate the infection rate over 10 complete dayas
agg_i10 <- aggregate(data_i10$Agegroup, by=list(data_i10$Agegroup), FUN=length)

agg_i10 <- agg_i10 %>%
          rename("Count" = "x") %>%
          rename("Agegroup" = "Group.1") %>%
    group_by(Agegroup) %>%
    mutate(Sum = sum(agg_i10$x)) %>%
    mutate(Proportion=(round(Count/Sum,4)))

#Note: in MATLAB we have agg_i10 = I_zero
#Now construct R_0 from agg_i and agg_i10
R0 = (agg_i$Count - agg_i10$Count)

#Now scale by randomized testing
#Extract data from papers

```

